swagger: '2.0'
info:
  title: 'Voting Session API'
  description: 'Voting Session API'
  version: 1.0.0
host: 'localhost:8080'

tags:
  - name: 'Agenda Controller'
    description: 'This is the controller to receive and respond to requests related to agendas'
paths:

  '/agenda':
    post:
      tags:
        - 'Agenda Controller'
      summary: 'Method to create a new agenda'
      operationId: 'createAgenda'
      consumes:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'AgendaRequestDTO'
          description: 'The agenda object'
          required: true
          schema:
            $ref: '#/definitions/AgendaRequestDTO'
      responses:
        '201':
          description: 'Created'
          schema:
            $ref: '#/definitions/AgendaRequestDTO'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      deprecated: false


definitions:

  AgendaRequestDTO:
    type: 'object'
    properties:
      name:
        type: 'string'
        example: 'Increase taxes for local internet providers'
        description: 'Name of the agenda'
      duration:
        type: 'integer'
        example: 60
        description: 'Duration of the agenda, expressed in minutes'
    title: 'AgendaRequestDTO'
