spring:
  data:
    mongodb:
      uri: ${DB_URI}
      auto-index-creation: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic